name: Close inactive issues
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  close-inactive-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Close inactive issues based on last response
        uses: actions/github-script@v6
        with:
          script: |
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
            });
            
            const { data: collaborators } = await github.rest.repos.listCollaborators({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            
            const memberLogins = collaborators.map(c => c.login);
            
            const now = new Date();
            const twoDaysInMs = 2 * 24 * 60 * 60 * 1000;
            
            console.log(`Found ${issues.length} open issues. Checking for inactivity...`);
            console.log(`Repository members: ${memberLogins.join(', ')}`);
            
            for (const issue of issues) {
              console.log(`Checking issue #${issue.number}: "${issue.title}"`);
              
              if (memberLogins.includes(issue.user.login)) {
                console.log(`Skipping issue #${issue.number} - created by repository member ${issue.user.login}`);
                continue;
              }
              
              const { data: timeline } = await github.rest.issues.listEventsForTimeline({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
              });
              
              const { data: comments } = await github.rest.issues.listComments({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
              });
              
              const allActivities = [
                {
                  type: 'created',
                  date: issue.created_at,
                  user: issue.user.login
                },
                ...comments.map(comment => ({
                  type: 'comment',
                  date: comment.updated_at,
                  user: comment.user.login
                })),
                ...timeline.map(event => ({
                  type: event.event,
                  date: event.created_at,
                  user: event.actor?.login
                })).filter(event => event.user)
              ];
              
              allActivities.sort((a, b) => new Date(b.date) - new Date(a.date));
              
              const lastActivity = allActivities[0];
              const lastActivityTime = new Date(lastActivity.date);
              const timeSinceLastActivity = now - lastActivityTime;
              
              console.log(`Issue #${issue.number}:`, {
                created: issue.created_at,
                lastActivity: lastActivity.date,
                lastActivityType: lastActivity.type,
                lastActivityUser: lastActivity.user,
                timeSinceLastActivityInDays: (timeSinceLastActivity / (24 * 60 * 60 * 1000)).toFixed(2),
                shouldClose: timeSinceLastActivity > twoDaysInMs
              });
              
              if (timeSinceLastActivity > twoDaysInMs) {
                console.log(`Closing issue #${issue.number} due to inactivity after last response`);
                
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  body: 'This issue hasn't had any new activity for a while after the last reply, so it’s been automatically closed. If you still need help, you can reopen it or create a new one.'
                });
                
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  state: 'closed',
                  state_reason: 'not_planned'
                });
                
                console.log(`Successfully closed issue #${issue.number}`);
              } else {
                console.log(`Issue #${issue.number} does not meet closure criteria`);
              }
            }
            
            console.log('Finished processing all issues');
